version: '3'
services:
  db:
    image: postgres:13-alpine
    ports:
      - 5433:5432

  frontend:
    image:
      ports:
        - 80:80

  backend:
    image:
      ports:
        - 3000:3000

  geoserver:
    image:
    ports: