version: '3'
services:
  db:
   image: postgres:9.6
   environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
   ports:
    - 5433:5432

  backend:
   image: python:3.6
   ports:
    - 3000:3000
   volumes:
    - ./backend:/backend
   working_dir: /backend
   command: bash ./backend.sh
