version: '3'
services:
  db:
   image: postgres:9.6
   environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
   ports:
    - 5433:5432

  frontend:
   image: node:8.1
   ports:
    - 8080:8080
   volumes:
    - ./frontend:/frontend
   working_dir: /usr/src/app
   command: bash -c "cd /frontend && npm install && node npm run dev"

  backend:
   image: python:3.6
   ports:
    - 3000:3000
   volumes:
    - ./backend:/backend
   working_dir: /backend
   command: bash ./backend.sh
